version: "3.3"

services:
    api:
        container_name: "${APP_NAME}-devserver"
        ports:
            - "${DEV_PORT}:80"
        environment:
            - "DATABASE_URL=mysql://${DEV_SQL_USER}:${DEV_SQL_PASSWD}@db:3306/${DEV_SQL_DB}?serverVersion=10.5"