controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

react_route:
    path: /{route}
    controller: App\Controller\HomeController::index
    requirements:
        route: .+